# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Persons/WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5300:5300
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
